version: '1'
services: 
    redis:
        image: redis:alpine
        # network_mode: host
        ports: 
            - "6379"
        container_name: backingredis

    proxy:
        build: .
        command:
            sh -c "dep ensure &&
                   go build && 
                   ./redis-proxy --capacity $CAPACITY --global-expiry $GLOBAL_EXPIRY --port $PORT --max-clients $MAX_CLIENTS --redis-address $REDIS_ADDRESS"
        links:
            - redis:redis
        depends_on:
            - redis
        ports:
            - "$PORT:$PORT" # host:container
        # volumes:
        #     - .:/go/src/github.com/helloworld/redis-proxy
        container_name: redis-proxy

