version: '3'
services: 
    redis:
        image: redis:alpine
        ports: 
            - "6379"
        container_name: backend-redis

    server:
        build: .
        command:
            sh -c "python3 src/proxy.py -c $CAPACITY -e $GLOBAL_EXPIRY -p $PORT -m $MAX_CLIENTS -r $REDIS_ADDRESS"
        links:
            - redis:redis
        depends_on:
            - redis
        ports:
            - "$PORT:$PORT"
        container_name: redis-proxy

